baseURL = "https://sevenofseven.site"
languageCode = "en-us"
title = "Seven of Seven"
theme = "castanet"
googleAnalytics = ""
disqusShortname = ""
paginate = "9"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

#[[Menu.Main]]
#    name = "Contact"
#    identifier = "contact"
#    url = "contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "host"

#[[Menu.Main]]
#    name = "Guests"
#    identifier = "guests"
#    url = "guest"

#[[Menu.Main]]
#    name = "Resources"
#    identifier = "resources"
#    url = "#!"

#[[Menu.Main]]
#    name = "Podcasts"
#    identifier = "podcasts"
#    url = "books"
#    parent = "resources"

[params]
site_theme = "grey"
site_layout = "grid"
enable_jumbo = "false"
# truncate = "100"
about_logo = "/img/7o7.png"
logo = "img/7o7.png"
copyright_notice = "Copyright 2019 [Seven of Seven](https://sevenofseven.site)"
itunes_subscribe = "https://podcasts.apple.com/us/podcast/seven-of-seven/id1478561577"
#android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/"
spotify_subscribe = "https://open.spotify.com/show/3sAb1T7tv7pXEu9nOV3y0L"
google_play_subscribe = "https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Isktun4sdxaegc33w7l5lcvrp4u?t%3DSeven_of_Seven%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16"
stitcher_subscribe = "https://www.stitcher.com/s?fid=460636&refid=stpr"
#soundcloud_subscribe = ""
#pocketcasts_subscribe = ""
#mailchimp_subscribe = ""
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Join Chief and Johnny as they explore the legendary cinematic masterpiece that set the world ablaze: SEVEN (No, not that one). They dissect the film in seven minute segments, unpacking the wild, wet, and weird world of Andy Sidaris and attempt to stay (relatively) sane in the process. SPOILER: They fail."
media_prefix = "https://sevenofseven.site/episodes/"
  [params.feed]
    copyright = "Copyright 2019 Seven of Seven" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "A podcast about the films of Andy Sidaris" #no markdown or HTML
    itunes_author = "Seven of Seven" #no markdown or HTML
    itunes_summary = "Join Chief and Johnny as they explore the legendary cinematic masterpiece that set the world ablaze: SEVEN (No, not that one). They dissect the film in seven minute segments, unpacking the wild, wet, and weird world of Andy Sidaris and attempt to stay (relatively) sane in the process. SPOILER: They fail." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Christopher Najewicz"
    itunes_owner_email = "chief@beefdisciple.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://sevenofseven.site/img/7o7-lg.png" #fqdn to the image art for your podcast
    itunes_top_category = "TV & Film"
    language = "en-us"
    explicit = "yes"

  [params.social]
    facebook = "sevenofseven"
    #facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "7of7podcast"
    twitter_domain = "sevenonseven.site" # This domain shows in twitter cards as "View on `twitter_domain`"

  [params.authors]
    [params.authors.Chief]
        name	= "Christopher 'Chief' Najewicz"
        thumbnail = "img/host/chief_md.jpg"
        bio = ""
        [params.authors.Chief.social]
            github = "chiefy"
            twitter = "tehsuck"
    [params.authors.Johnny]
        name = "John Miller"
        thumbnail = "img/host/johnny.jpg"
        bio = ""
        [params.authors.Johnny.social]
            twitter = "johnnyanarchy"

    [params.links]
